config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'

  get 'cycles/dt'
  get 'cycles/getall'

  get 'complaints/getall'

  get 'dashboard/getpie'
  get 'dashboard/getcomplaints'

  resources :cycles

  resources :complaints

  resources :productions

  resources :locations

  resources :defect_types

  resources :sizes

  resources :flavors

  resources :users

  root 'dashboard#index'

end

app/models/flavor.rb
class Flavor < ActiveRecord::Base
  has_many :cycle
end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
  before_action :set_flavor, only: [:show, :edit, :update, :destroy]

  # GET /flavors
  # GET /flavors.json
  def index
    @flavors = Flavor.all
  end

  # GET /flavors/1
  # GET /flavors/1.json
  def show
  end

  # GET /flavors/new
  def new
    @flavor = Flavor.new
  end

  # GET /flavors/1/edit
  def edit
  end

  # POST /flavors
  # POST /flavors.json
  def create
    @flavor = Flavor.new(flavor_params)

    respond_to do |format|
      if @flavor.save
        format.html { redirect_to @flavor, notice: 'Flavor was successfully created.' }
        format.json { render :show, status: :created, location: @flavor }
      else
        format.html { render :new }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flavors/1
  # PATCH/PUT /flavors/1.json
  def update
    respond_to do |format|
      if @flavor.update(flavor_params)
        format.html { redirect_to @flavor, notice: 'Flavor was successfully updated.' }
        format.json { render :show, status: :ok, location: @flavor }
      else
        format.html { render :edit }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flavors/1
  # DELETE /flavors/1.json
  def destroy
    @flavor.destroy
    respond_to do |format|
      format.html { redirect_to flavors_url, notice: 'Flavor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flavor
      @flavor = Flavor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flavor_params
      params.require(:flavor).permit(:name)
    end
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/views/flavors/_form.html.erb
<%= form_for(@flavor) do |f| %>
  <% if @flavor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flavor.errors.count, "error") %> prohibited this flavor from being saved:</h2>

      <ul>
      <% @flavor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flavors/edit.html.erb
<h1>Editing flavor</h1>

<%= render 'form' %>

<%= link_to 'Show', @flavor %> |
<%= link_to 'Back', flavors_path %>

app/views/flavors/index.html.erb
<h1>Flavors</h1>
<%= link_to 'Add New Flavor', new_flavor_path, :class => 'btn btn-large btn-primary' %>
<table class="table table-striped table-hover" style="font-size: 10px;">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flavors.each do |flavor| %>
      <tr>
        <td style="font-size: 10px;"><%= flavor.name %></td>
        <td style="font-size: 10px; width: 20px;"><%= link_to('Show', flavor, :class => 'btn btn-xs btn-primary')  %></td>
        <td style="font-size: 10px; width: 20px;"><%= link_to('Edit', edit_flavor_path(flavor), :class => 'btn btn-xs btn-warning')  %></td>
        <td style="font-size: 10px; width: 20px;"><%= link_to('Destroy', flavor, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-danger')  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/flavors/new.html.erb
<h1>New flavor</h1>

<%= render 'form' %>

<%= link_to 'Back', flavors_path %>

app/views/flavors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flavor.name %>
</p>

<%= link_to 'Edit', edit_flavor_path(@flavor) %> |
<%= link_to 'Back', flavors_path %>