config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'

  get 'cycles/dt'
  get 'cycles/getall'

  get 'complaints/getall'

  get 'dashboard/getpie'
  get 'dashboard/getcomplaints'

  resources :cycles

  resources :complaints

  resources :productions

  resources :locations

  resources :defect_types

  resources :sizes

  resources :flavors

  resources :users

  root 'dashboard#index'

end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /complaints
  # GET /complaints.json
  def index
    @complaints = Complaint.all
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
  end

def getall
    complaints = Complaint.all
    hash = Hash.new
    hash[:data] = []
    complaints.each do |complaint|
      temp_array = []
      temp_array << complaint.id
      temp_array << complaint.date.strftime("%m/%d/%Y")
      temp_array << complaint.product
      temp_array << complaint.reason
      temp_array << complaint.synopsis
      temp_array << complaint.notes
      temp_array << complaint.store_number
      temp_array << complaint.store_name
      temp_array << complaint.city
      temp_array << complaint.state
      temp_array << complaint.coding_level2
      temp_array << complaint.brand_code
      temp_array << complaint.brand
      temp_array << complaint.ownership_type
      temp_array << complaint.duplicate
      hash[:data] << temp_array
    end
    render json: hash
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
  def create
    @complaint = Complaint.new(complaint_params)

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
        format.json { render :show, status: :created, location: @complaint }
      else
        format.html { render :new }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params
      params.require(:complaint).permit(:date, :product, :reason, :synopsis, :notes, :store_number, :store_name, :city, :state, :coding_level2, :brand_code, :brand, :ownership_type, :duplicate)
    end
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/views/complaints/_form.html.erb
<%= form_for(@complaint) do |f| %>
  <% if @complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
      <% @complaint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-group">
    <%= f.label :date %><br>
    <%= f.datetime_select :date , :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product , :class => 'form-control input-sm' %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason , :class => 'form-control input-sm' %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br>
    <%= f.text_area :synopsis , :class => 'form-control input-sm'  %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes , :class => 'form-control input-sm'  %>
  </div>
  <div class="field">
    <%= f.label :store_number %><br>
    <%= f.number_field :store_number , :class => 'form-control input-sm'  %>
  </div>
  <div class="field">
    <%= f.label :store_name %><br>
    <%= f.text_field :store_name , :class => 'form-control input-sm'  %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city , :class => 'form-control input-sm' %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state , :class => 'form-control input-sm' %>
  </div>
  <div class="field">
    <%= f.label :coding_level2 %><br>
    <%= f.text_field :coding_level2 , :class => 'form-control input-sm' %>
  </div>
  <div class="field">
    <%= f.label :brand_code %><br>
    <%= f.text_field :brand_code , :class => 'form-control input-sm' %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand , :class => 'form-control input-sm' %>
  </div>
  <div class="field">
    <%= f.label :ownership_type %><br>
    <%= f.text_field :ownership_type , :class => 'form-control input-sm' %>
  </div>
  <div class="field">
    <%= f.label :duplicate %><br>
    <%= f.check_box :duplicate , :class => 'form-control input-sm' %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-xs btn-primary' %>
  </div>
<% end %>

app/views/complaints/edit.html.erb
<h1>Editing complaint</h1>

<%= render 'form' %>

<%= link_to 'Show', @complaint %> |
<%= link_to 'Back', complaints_path %>

app/views/complaints/index.html.erb
<script type="text/javascript">
 $(function() {
    $('a').tooltip({placement: 'right'});
});

 $(document).ready(function() {
    $('#example').dataTable( {
        "search": {  "regex": true },
        "ajax": "/complaints/getall",
        "deferRender": true,
    } );
} );


</script>
<style>
   .dataTable th, .dataTable td {
       max-width: 200px;
       min-width: 70px;
       overflow: hidden;
       text-overflow: ellipsis;
       white-space: nowrap;
       font-size: 10px;
  }
</style>
<h1>Complaints</h1>
<%= link_to 'Add New Complaint', new_complaint_path, :class => 'btn btn-large btn-primary' %>
<table id="example" class="display" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>ID</th>
      <th>Date</th>
      <th>Product</th>
      <th>Reason</th>
      <th>Synopsis</th>
      <th>Notes</th>
      <th>Store number</th>
      <th>Store name</th>
      <th>City</th>
      <th>State</th>
      <th>Coding level2</th>
      <th>Brand code</th>
      <th>Brand</th>
      <th>Ownership type</th>
      <th>Duplicate</th>
    </tr>
  </thead>


  <tfoot>
    <tr>
      <th>ID</th>
      <th>Date</th>
      <th>Product</th>
      <th>Reason</th>
      <th>Synopsis</th>
      <th>Notes</th>
      <th>Store number</th>
      <th>Store name</th>
      <th>City</th>
      <th>State</th>
      <th>Coding level2</th>
      <th>Brand code</th>
      <th>Brand</th>
      <th>Ownership type</th>
      <th>Duplicate</th>
      </tr>
  </tfoot>
  </table>

app/views/complaints/new.html.erb
<h1>Add New Complaint</h1>

<%= render 'form' %>

<%= link_to 'Back', complaints_path %>

app/views/complaints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @complaint.date %>
</p>

<p>
  <strong>Product:</strong>
  <%= @complaint.product %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @complaint.reason %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @complaint.synopsis %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @complaint.notes %>
</p>

<p>
  <strong>Store number:</strong>
  <%= @complaint.store_number %>
</p>

<p>
  <strong>Store name:</strong>
  <%= @complaint.store_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @complaint.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @complaint.state %>
</p>

<p>
  <strong>Coding level2:</strong>
  <%= @complaint.coding_level2 %>
</p>

<p>
  <strong>Brand code:</strong>
  <%= @complaint.brand_code %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @complaint.brand %>
</p>

<p>
  <strong>Ownership type:</strong>
  <%= @complaint.ownership_type %>
</p>

<p>
  <strong>Duplicate:</strong>
  <%= @complaint.duplicate %>
</p>

<%= link_to 'Edit', edit_complaint_path(@complaint) %> |
<%= link_to 'Back', complaints_path %>