config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'

  get 'cycles/dt'
  get 'cycles/getall'

  get 'complaints/getall'

  get 'dashboard/getpie'
  get 'dashboard/getcomplaints'

  resources :cycles

  resources :complaints

  resources :productions

  resources :locations

  resources :defect_types

  resources :sizes

  resources :flavors

  resources :users

  root 'dashboard#index'

end

app/controllers/defect_types_controller.rb
class DefectTypesController < ApplicationController
  before_action :set_defect_type, only: [:show, :edit, :update, :destroy]

  # GET /defect_types
  # GET /defect_types.json
  def index
    @defect_types = DefectType.all
  end

  # GET /defect_types/1
  # GET /defect_types/1.json
  def show
  end

  # GET /defect_types/new
  def new
    @defect_type = DefectType.new
  end

  # GET /defect_types/1/edit
  def edit
  end

  # POST /defect_types
  # POST /defect_types.json
  def create
    @defect_type = DefectType.new(defect_type_params)

    respond_to do |format|
      if @defect_type.save
        format.html { redirect_to @defect_type, notice: 'Defect type was successfully created.' }
        format.json { render :show, status: :created, location: @defect_type }
      else
        format.html { render :new }
        format.json { render json: @defect_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /defect_types/1
  # PATCH/PUT /defect_types/1.json
  def update
    respond_to do |format|
      if @defect_type.update(defect_type_params)
        format.html { redirect_to @defect_type, notice: 'Defect type was successfully updated.' }
        format.json { render :show, status: :ok, location: @defect_type }
      else
        format.html { render :edit }
        format.json { render json: @defect_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /defect_types/1
  # DELETE /defect_types/1.json
  def destroy
    @defect_type.destroy
    respond_to do |format|
      format.html { redirect_to defect_types_url, notice: 'Defect type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_defect_type
      @defect_type = DefectType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def defect_type_params
      params.require(:defect_type).permit(:name, :sbuxid)
    end
end

app/helpers/defect_types_helper.rb
module DefectTypesHelper
end

app/views/defect_types/_form.html.erb
<%= form_for @defect_type, html: {:class => "form-horizontal col-md-offset-1 col-md-8"} do |f| %>
  <% if @defect_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@defect_type.errors.count, "error") %> prohibited this defect_type from being saved:</h2>

      <ul>
      <% @defect_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :sbuxid %><br>
    <%= f.number_field :sbuxid, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-default"%>
  </div>
<% end %>

app/views/defect_types/edit.html.erb
<h1>Editing defect_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @defect_type %> |
<%= link_to 'Back', defect_types_path %>

app/views/defect_types/index.html.erb
<h1>Defect Types</h1>
<%= link_to 'Add New Defect Type', new_defect_type_path, :class => 'btn btn-large btn-primary' %>
<table class="table table-striped table-hover" style="font-size: 10px;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Sbuxid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @defect_types.each do |defect_type| %>
      <tr>
        <td style="font-size: 10px;"><%= defect_type.name %></td>
        <td style="font-size: 10px;"><%= defect_type.sbuxid %></td>
        <td style="font-size: 10px; width: 20px"><%= link_to('Show', defect_type, :class => 'btn btn-xs btn-primary')  %></td>
        <td style="font-size: 10px; width: 20px"><%= link_to('Edit', edit_defect_type_path(defect_type), :class => 'btn btn-xs btn-warning')  %></td>
        <td style="font-size: 10px; width: 20px"><%= link_to('Destroy', defect_type, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-danger')  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/defect_types/new.html.erb
<h1>New Defect Type</h1>

<%= render 'form' %>
<div class="row">
<%= link_to 'Back', defect_types_path, :class => "btn btn-default" %>
</div>

app/views/defect_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @defect_type.name %>
</p>

<p>
  <strong>Sbuxid:</strong>
  <%= @defect_type.sbuxid %>
</p>

<%= link_to 'Edit', edit_defect_type_path(@defect_type) %> |
<%= link_to 'Back', defect_types_path %>